name: Build awslogin
on:
    release:
        types:
            - published
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup go
      uses: actions/setup-go@v1
      with:
        go-version: '1.14'
    - name: Compile
      run: make all
    - name: mac awslogin artifact
      uses: actions/upload-artifact@v1
      with:
        name: awslogin
        path: awslogin
    - name: linux awslogin artifact
      uses: actions/upload-artifact@v1
      with:
        name: awslogin-linux
        path: awslogin-linux
